### ISSUE TITLE
连接服务超时的问题

### ISSUE THREAD

**Issue by ZhuoSir** [ashinnotfound/ChatGPT-YourChatRobot#58]
我本地有翻墙软件，而且可以通过API访问chatgpt，但是通过这个服务却响应超时，这是什么原因 ？

**Comment by ZhuoSir** [comment]
java.lang.RuntimeException: java.net.SocketTimeoutException: connect timed out
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:46)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:93)
	at io.reactivex.Single.blockingGet(Single.java:2870)
	at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:218)
	at com.theokanning.openai.service.OpenAiService.createChatCompletion(OpenAiService.java:93)
	at com.ashin.service.impl.InteractServiceImpl.chat(InteractServiceImpl.java:37)
	at com.ashin.handler.WechatMessageHandler.textMsgHandle(WechatMessageHandler.java:62)
	at cn.zhouyafeng.itchat4j.core.MsgCenter.handleMsg(MsgCenter.java:130)
	at cn.zhouyafeng.itchat4j.Wechat$1.run(Wechat.java:28)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: connect timed out

**Comment by ashinnotfound** [comment]
要配置配置文件里的proxy
